openapi: 3.0.1
info:
  title: UsersAuthorization API
  version: v1
paths:
  /api/v1/auth/register:
    post:
      tags:
        - Auth
      summary: Registers a user and return it
      operationId: RegisterUser
      security:
        - Bearer: []
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RegisterRequestDTO'
          text/json:
            schema:
              $ref: '#/components/schemas/RegisterRequestDTO'
          application/*+json:
            schema:
              $ref: '#/components/schemas/RegisterRequestDTO'
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/StringResponseDTO'
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ObjectResponseDTO'
  /api/v1/auth/login:
    post:
      tags:
        - Auth
      summary: Log in the user and return a
      operationId: LoginUser
      security:
        - Bearer: []
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/LoginRequestDTO'
          text/json:
            schema:
              $ref: '#/components/schemas/LoginRequestDTO'
          application/*+json:
            schema:
              $ref: '#/components/schemas/LoginRequestDTO'
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/LoginResponseDTOResponseDTO'
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ObjectResponseDTO'
components:
  schemas:
    LoginRequestDTO:
      type: object
      properties:
        username:
          type: string
          nullable: true
        password:
          type: string
          nullable: true
      additionalProperties: false
    LoginResponseDTO:
      type: object
      properties:
        user:
          $ref: '#/components/schemas/UserDTO'
        token:
          type: string
          nullable: true
      additionalProperties: false
    LoginResponseDTOResponseDTO:
      type: object
      properties:
        result:
          $ref: '#/components/schemas/LoginResponseDTO'
        isSuccess:
          type: boolean
        message:
          type: string
          nullable: true
      additionalProperties: false
    ObjectResponseDTO:
      type: object
      properties:
        result:
          nullable: true
        isSuccess:
          type: boolean
        message:
          type: string
          nullable: true
      additionalProperties: false
    RegisterRequestDTO:
      type: object
      properties:
        name:
          type: string
          nullable: true
        email:
          type: string
          nullable: true
        password:
          type: string
          nullable: true
      additionalProperties: false
    StringResponseDTO:
      type: object
      properties:
        result:
          type: string
          nullable: true
        isSuccess:
          type: boolean
        message:
          type: string
          nullable: true
      additionalProperties: false
    UserDTO:
      type: object
      properties:
        id:
          type: integer
          format: int32
        name:
          type: string
          nullable: true
        email:
          type: string
          nullable: true
        status:
          type: string
          nullable: true
      additionalProperties: false
  securitySchemes:
    Bearer:
      type: http
      description: 'JWT: Bearer {token}'
      scheme: Bearer
